repositories:
  - name: nginx
    url: https://helm.nginx.com/stable
  - name: jetstack
    url: https://charts.jetstack.io
  - name: argocd
    url: https://argoproj.github.io/argo-helm
releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart: nginx/nginx-ingress
    values:
      - rbac.create: true
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - installCRDs: true
      - global.rbac.create: true
  - name: argocd
    namespace: argocd
    chart: argocd/argo-cd
    values:
      - installCRDs: false
      - server:
          extraArgs:
            - "--insecure"
