---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
    - hosts:
        - argocd.colecarter.dev
      secretName: argocd-secret
  rules:
    - host: argocd.colecarter.dev
      http:
        paths:
        - path: /
          backend:
            serviceName: argocd-server
            servicePort: https
